### ISSUE TITLE
remove usage of `forc_util`

### ISSUE THREAD

**Issue by spiral-ladder** [FuelLabs/forc-explorer#6]
`forc-explore` still depends on `forc-util` package within the Sway repo, but the only usage of this is to init the `tracing_subscriber`. To avoid depending on forc-util entirely we could just extract the [`init_tracing_subscriber` function](https://github.com/FuelLabs/sway/blob/897e70b5a13ea95a1aaedc9a697312087e5a3ecb/forc-util/src/lib.rs#L430) it uses here instead. 

Of course this would be a slight inconvenience since any changes to the subscriber would potentially have to be copied here if we want tracing to behave exactly the same, but my impression is that the tracing subscriber won't undergo too many changes generally, and it would be trivial to apply changes in both repos either way.

cc @FuelLabs/tooling for thoughts

**Comment by mitchmindtree** [comment]
@bingcicle Perhaps we can extract the `tracing` stuff into a tiny `forc-tracing` crate? This might be useful in general for 3rd party plugins that want uniform logging behaviour with `forc` but without all the `forc-util` dependencies (which includes the entirety of `sway-core` heh).

**Comment by spiral-ladder** [comment]
That's a good suggestion. I take it as this new `forc-tracing` will be a standalone repo?

edit: either that or we would have to create a separate github workflow within `sway` repo in charge of releasing/bumping `forc-util`. but that could cause confusion

**Comment by mitchmindtree** [comment]
> I take it as this new forc-tracing will be a standalone repo?

Yeah I think I'd keep it in the `sway` repo alongside `forc-util`, `forc-pkg` and `forc`.
